apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hello-nkp.fullname" . }}-hello
  labels:
  {{- include "hello-nkp.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: kommander-traefik
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "hello-nkp.fullname" . }}-hello'
            port:
              number: 80
        path: /hello
        pathType: ImplementationSpecific
